#!/bin/sh
if [ "$(whoami)" != "root" ];then
  echo "Need to be root or run with sudo. Exiting."
  exit 1
fi

dpkg --add-architecture i386
wget -nc -O /usr/share/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
apt update
apt install --install-recommends winehq-devel playonlinux q4wine
wget -nc -P /usr/share/applications https://raw.githubusercontent.com/Jin-Asanami/kamuriki-utils/main/winehq/wine-wimecfg.desktop
wget -nc -P /usr/share/applications https://raw.githubusercontent.com/Jin-Asanami/kamuriki-utils/main/winehq/wine-uninstaller.desktop
